export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; // Add this
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const GET_PROPERTIES = 'GET_PROPERTIES';
export const PROPERTY_ERROR = 'PROPERTY_ERROR';
export const LIKE_PROPERTY = 'LIKE_PROPERTY'; // Add this
